### ISSUE TITLE
/Feature/Tournament

### ISSUE THREAD

**Issue by V0lk7** [DoubleV37/ft_transcendence#140]
### Create the Tournament

- [ ] Define the data structure in the front
- [ ] Create the HTML which will handle all the process.
- [ ] Step 0: Implement the fields of the type of the game. (point_count:int, power-up: bool)
- [ ] Step 1: Implement the User creation fields of the tournament player.
- [ ] Step 2: Create the visualization of the tournament.
- [ ] Step 3: Handle the behavior and the switch on the different games.
- [ ] Step 4: Handle the end of the tournament.

**Comment by V0lk7** [comment]
### TODO

- [ ] Erase the Join tournament button
- [ ] Handle the create button to be like the custom game create button
- [ ] Make it go after to the username player creation
